### ISSUE TITLE
Compiling the FPGA code

### ISSUE THREAD

**Issue by altineller** [will127534/IMU_Array#3]
Hello,

When I run the command 'iverilog -o test ./spi_slave.v ./spi_testbench.v' from run_testbench.sh, I get the following warnings regarding line 14:

`./spi_testbench.v:14: warning: extra digits given for sized hex constant.
./spi_testbench.v:14: warning: Numeric constant truncated to 8 bits.
`

Line 14 is:

    initial testdata = 8'h1275;

I undertsand that this is just a warning, but is this a typo, or is it running correctly, because it seems that the constant is truncated?
Is it a typo maybe?

Best Regards,
Can

**Comment by will127534** [comment]
That is not used in the actual test, so should be fine.
